site_name: Fuchsia中文文档测试
repo_url: https://github.com/y2-Whyto/FuchsiaOS-docs-zh_CN
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  logo: https://fuchsia-china.com/wp-content/uploads/2022/07/fuchsia-new-trans-outlined.png
  favicon: https://fuchsia-china.com/wp-content/uploads/2022/07/fuchsia-new-logo-2.png
  features:
    - navigation.top
