site_name: Fuchsia中文文档
repo_url: https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN
site_author: Fuchsia中文文档翻译小组
copyright: Fuchsia中文社区
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  logo: https://fuchsia-china.com/wp-content/uploads/2022/07/fuchsia-new-logo-white.png
  favicon: https://fuchsia-china.com/wp-content/uploads/2022/07/fuchsia-new-logo-outlined.png
  features:
    - navigation.top
